import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import 'primeflex/primeflex.css';
// import 'primeicons/primeicons.css';
// import { PrimeReactProvider } from 'primereact/api';
// import 'primereact/resources/primereact.min.css';
// import 'primereact/resources/themes/lara-light-indigo/theme.css';
import './globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Enghouse Login",
  description: "Generated by create next app",
};

// app/layout.tsx
import PrimeReactWrapper from '@/app/components/PrimeReactWrapper';
import "primereact/resources/themes/lara-light-cyan/theme.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PrimeReactWrapper>
          {children}
        </PrimeReactWrapper>
      </body>
    </html>
  );
}
